// <auto-generated />
using Cargo.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cargo.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250324184142_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cargo.Api.Infrastructure.Domain.CargoEntity", b =>
                {
                    b.Property<long>("Cargo_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Cargo_ID"));

                    b.Property<long>("Transporter_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("Vehicle_ID")
                        .HasColumnType("bigint");

                    b.HasKey("Cargo_ID");

                    b.ToTable("Cargos");
                });
#pragma warning restore 612, 618
        }
    }
}
